### ISSUE TITLE
Paragraph create does not work for all docx files

### ISSUE THREAD

**Issue by campgurus** [campgurus/writersapp#15]
This work perfectly for some files., but other files generate the following error:

`undefined method `path' for #<StringIO:0x007fa385a7c580>`

Attaching an example of  a failing .docx file:
[jadenpn.docx](https://github.com/campgurus/writersapp/files/949455/jadenpn.docx)

full trace:
```
Started POST "/writings" for 127.0.0.1 at 2017-04-23 00:04:26 -0400
Processing by WritingsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"3vH+VCM6duYSq60Se1i0bAFPX5GoYKlok66m7eREca0tc0V5tCAzsiCFXSf90MTB9C7mmwm0j36MrxYuJCAYnA==", "writing"=>{"name"=>"v game teacher", "document"=>#<ActionDispatch::Http::UploadedFile:0x007fa384c80580 @tempfile=#<Tempfile:/var/folders/q5/qnv_p0j94jxdt8kwj7ky_7th0000gn/T/RackMultipart20170423-9007-1yef4re.docx>, @original_filename="jadenpn.docx", @content_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document", @headers="Content-Disposition: form-data; name=\"writing[document]\"; filename=\"jadenpn.docx\"\r\nContent-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document\r\n">}, "commit"=>"Save"}
   (0.2ms)  BEGIN
  SQL (0.3ms)  INSERT INTO "writings" ("name", "document", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["name", "v game teacher"], ["document", "jadenpn.docx"], ["created_at", 2017-04-23 04:04:26 UTC], ["updated_at", 2017-04-23 04:04:26 UTC]]
   (0.5ms)  ROLLBACK
Completed 500 Internal Server Error in 319ms (ActiveRecord: 0.9ms)


  
NoMethodError (undefined method `path' for #<StringIO:0x007fa385a7c580>):
  
app/models/writing.rb:15:in `create_paragraphs'
app/controllers/writings_controller.rb:32:in `block in create'
app/controllers/writings_controller.rb:31:in `create'
  Rendering /Users/dariusgoore/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout
  Rendering /Users/dariusgoore/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
  Rendered /Users/dariusgoore/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_source.html.erb (6.0ms)
  Rendering /Users/dariusgoore/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered /Users/dariusgoore/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.0ms)
  Rendering /Users/dariusgoore/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
  Rendered /Users/dariusgoore/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.0ms)
  Rendered /Users/dariusgoore/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (64.3ms)
```

**Comment by campgurus** [comment]
Recognizing this issue exists and is still unresolved, I am stil going to try to get the  comments feature to work in the meantime.
