### ISSUE TITLE
User should be able to comment on a Paragraph in a Writing

### ISSUE THREAD

**Issue by campgurus** [campgurus/writersapp#16]
This is not fully functional at this point.

So far, we have created the three models, Writing, Paragraph and Comment, s.t. Comment belongs to Paragraph (as commentable) and Paragraph belongs to Writing.  Writing has_many Comments thru Paragraphs.

In console, the functionality works. We can create a new comment with Paragraph.find().comments.create(:body), and all relationships seem operative. we can find the comment among @paragraph.comments as well as @article.comments.

The issue is in creating the model instance via the UI. 

Specifically I can't seem to pass the paragraph_id to the controller or the route, and

```<%= link_to new_writing_paragraph_comment_path (@writing, p) do %>
			<span data-toggle="tooltip" data-placement="top" title="Add Comment">
			  <%= fa_icon "comment" %>
			</span>
		<% end %>```

is throwing the error:
```/Users/dariusgoore/development/writersapp/app/views/writings/show.html.erb:5: syntax error, unexpected ')', expecting '=' aph_comment_path (@writing, p) do @output_buffer.safe_append ^ /Users/dariusgoore/development/writersapp/app/views/writings/show.html.erb:15: syntax error, unexpected keyword_ensure, expecting end-of-input ensure ^```

Full trace;
```app/views/writings/show.html.erb:5: syntax error, unexpected ')', expecting '='
aph_comment_path (@writing, p) do @output_buffer.safe_append
                              ^
app/views/writings/show.html.erb:15: syntax error, unexpected keyword_ensure, expecting end-of-input
          ensure
                ^
actionview (5.0.1) lib/action_view/template.rb:310:in `module_eval'
actionview (5.0.1) lib/action_view/template.rb:310:in `compile'
actionview (5.0.1) lib/action_view/template.rb:259:in `block (2 levels) in compile!'
activesupport (5.0.1) lib/active_support/notifications.rb:166:in `instrument'
actionview (5.0.1) lib/action_view/template.rb:356:in `instrument'
actionview (5.0.1) lib/action_view/template.rb:258:in `block in compile!'
actionview (5.0.1) lib/action_view/template.rb:246:in `synchronize'
actionview (5.0.1) lib/action_view/template.rb:246:in `compile!'
actionview (5.0.1) lib/action_view/template.rb:158:in `block in render'
activesupport (5.0.1) lib/active_support/notifications.rb:166:in `instrument'
actionview (5.0.1) lib/action_view/template.rb:354:in `instrument'
actionview (5.0.1) lib/action_view/template.rb:157:in `render'
actionview (5.0.1) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
actionview (5.0.1) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `instrument'
actionview (5.0.1) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
actionview (5.0.1) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
actionview (5.0.1) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
actionview (5.0.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
actionview (5.0.1) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (5.0.1) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (5.0.1) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (5.0.1) lib/action_view/rendering.rb:103:in `_render_template'
actionpack (5.0.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (5.0.1) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (5.0.1) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (5.0.1) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
actionpack (5.0.1) lib/abstract_controller/rendering.rb:26:in `render'
actionpack (5.0.1) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (5.0.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/Users/dariusgoore/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
activesupport (5.0.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (5.0.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
actionpack (5.0.1) lib/action_controller/metal/implicit_render.rb:36:in `default_render'
actionpack (5.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `block in send_action'
actionpack (5.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `tap'
actionpack (5.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.0.1) lib/abstract_controller/base.rb:188:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.0.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.0.1) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.1) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
activesupport (5.0.1) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `instrument'
actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
activerecord (5.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (5.0.1) lib/abstract_controller/base.rb:126:in `process'
actionview (5.0.1) lib/action_view/rendering.rb:30:in `process'
actionpack (5.0.1) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.1) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.1) lib/rack/etag.rb:25:in `call'
rack (2.0.1) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.1) lib/rack/head.rb:12:in `call'
rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.0.1) lib/active_record/migration.rb:553:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
web-console (3.4.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.4.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.4.0) lib/web_console/middleware.rb:18:in `catch'
web-console (3.4.0) lib/web_console/middleware.rb:18:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/method_override.rb:22:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
railties (5.0.1) lib/rails/engine.rb:522:in `call'
puma (3.7.0) lib/puma/configuration.rb:226:in `call'
puma (3.7.0) lib/puma/server.rb:578:in `handle_request'
puma (3.7.0) lib/puma/server.rb:415:in `process_client'
puma (3.7.0) lib/puma/server.rb:275:in `block in run'
puma (3.7.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
Request

Parameters:

{"id"=>"3"}```

**Comment by campgurus** [comment]
After getting rid of the hyper-nested routes, we have gotten to the point where we should be able to  comment on paragraphs. the current issue is that the loop in the view:

```
<% @doc.paragraphs.compact.each do |p| %>
	<%= a=raw(p.to_html) %>
	<% if !strip_tags(a).empty? %>
		<%= link_to new_paragraph_comment_path (p) do %>
			<span data-toggle="tooltip" data-placement="top" title="Add Comment">
			  <%= fa_icon "comment" %>
			</span>
		<% end %>
	<% end %>
<% end %>
```
refers not to the Paragraph instances associated with the writing, but docx gem paragraphs created specifically in the view.  As a result the route helper does not have a model to refer to to generate the view route.

One solution we discussed was to eliminate the callback and create the Paragraph instances, when the comment is created. The downside of this is that eventually we still have to reconcile the paragraphs created in the view with those existing instances of Paragraph model.

The alternative is in the view to eliminate the reference to the docx gem paragraphs method, and refer instead to @writing.paragraphs.

**Comment by campgurus** [comment]
this works now. need eventually eliminate excess paragraphs created in cllback and potentially ajaxify this function
