### ISSUE TITLE
Difficulting pulling out relevant text from docs

### ISSUE THREAD

**Issue by campgurus** [campgurus/writersapp#2]
Here i what i have done so far in console:

url = Writing.first.document.url
 => "https://writersapp.s3.amazonaws.com/uploads/writing/document/3/Summer_Reading_Assignment_Joyful_Noise.docx" 

doc = Docx::Document.open(open(url).path)
 => #<Docx::Document:0x007fc7526baa78 @replace={}, @zip=#<Zip::File:0x007fc7526baa28 ...

I can command-f to find all phrases in the document, but i can't figure out how to pull just a paragraph, without all of the formatting gook.

By the way, this does not work for all of the docx files.  e.g if url = Writing.find(7).document.url. but that is an issue for when we get this to work witha single document.

Meanwhile, I can't believe no one has solved this problem with a workign gem.

docx gem loks like it hasn't been updated since 2014, which is probably not a good sign

**Comment by trystant** [comment]
From the README:

```
require 'docx'

# Create a Docx::Document object for our existing docx file
doc = Docx::Document.open('example.docx')

# RELEVANT CODE BEGINS HERE
# Retrieve and display paragraphs 
doc.paragraphs.each do |p|
  puts p
end
# RELEVANT CODE ENDS HERE

# Retrieve and display bookmarks, returned as hash with bookmark names as keys and objects as values
doc.bookmarks.each_pair do |bookmark_name, bookmark_object|
  puts bookmark_name
end
```

**Comment by campgurus** [comment]
i tried to follow the readme example but i get an error as follows:

```2.4.1 :019 > url = Writing.first.document.url
  Writing Load (0.3ms)  SELECT  "writings".* FROM "writings" ORDER BY "writings"."id" ASC LIMIT $1  [["LIMIT", 1]]
 => "https://writersapp.s3.amazonaws.com/uploads/writing/document/3/Summer_Reading_Assignment_Joyful_Noise.docx" 
2.4.1 :020 > doc = Docx::Document.open("https://writersapp.s3.amazonaws.com/uploads/writing/document/3/Summer_Reading_Assignment_Joyful_Noise.docx")
Zip::Error: File https://writersapp.s3.amazonaws.com/uploads/writing/document/3/Summer_Reading_Assignment_Joyful_Noise.docx not found
	from /Users/dariusgoore/.rvm/gems/ruby-2.4.1/gems/rubyzip-1.1.7/lib/zip/file.rb:82:in `initialize'
	from /Users/dariusgoore/.rvm/gems/ruby-2.4.1/gems/rubyzip-1.1.7/lib/zip/file.rb:96:in `new'
	from /Users/dariusgoore/.rvm/gems/ruby-2.4.1/gems/rubyzip-1.1.7/lib/zip/file.rb:96:in `open'
	from /Users/dariusgoore/.rvm/gems/ruby-2.4.1/gems/docx-0.2.07/lib/docx/document.rb:25:in `initialize'
	from /Users/dariusgoore/.rvm/gems/ruby-2.4.1/gems/docx-0.2.07/lib/docx/document.rb:50:in `new'
	from /Users/dariusgoore/.rvm/gems/ruby-2.4.1/gems/docx-0.2.07/lib/docx/document.rb:50:in `open'
	from (irb):20
	from /Users/dariusgoore/.rvm/gems/ruby-2.4.1/gems/railties-5.0.1/lib/rails/commands/console.rb:65:in `start'
	from /Users/dariusgoore/.rvm/gems/ruby-2.4.1/gems/railties-5.0.1/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/dariusgoore/.rvm/gems/ruby-2.4.1/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/dariusgoore/.rvm/gems/ruby-2.4.1/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/dariusgoore/.rvm/gems/ruby-2.4.1/gems/railties-5.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/dariusgoore/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/dariusgoore/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/dariusgoore/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/dariusgoore/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/dariusgoore/development/writersapp/bin/rails:9:in `<top (required)>'
	from /Users/dariusgoore/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/dariusgoore/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `block in load'
	from /Users/dariusgoore/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/dariusgoore/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/dariusgoore/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/dariusgoore/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'```

so i used: doc = Docx::Document.open(open(url).path) instead
which at least returned the object

doc.paragraphs.count returned a number of paragraphs as expected.

but how do i get the actual text to put on screen. that is my current dilemma

**Comment by trystant** [comment]
```
# Retrieve and display paragraphs
doc.paragraphs.each do |p|
  puts p
end
```

**Comment by trystant** [comment]
Also,

```
# Retrieve and display paragraphs as html
doc.paragraphs.each do |p|
  puts p.to_html
end
```

**Comment by campgurus** [comment]
i tried this:

```
2.4.1 :023 > doc.paragraphs.count
 => 32 
2.4.1 :024 > puts doc.paragraphs.first

 => nil 
2.4.1 :025 > 
```

**Comment by trystant** [comment]
and what about the other paragraphs? There are 31 others. Run the `each` command for reading.

**Comment by campgurus** [comment]
closing this as resolved
